"""Inbox warming — build sender reputation before cold outreach campaigns."""
import logging
from datetime import datetime, timedelta
from typing import Optional

logger = logging.getLogger(__name__)


def create_warming_schedule(
    from_email: str,
    from_name: str,
    start_date: str = "",
    duration_days: int = 14,
    target_daily_volume: int = 50,
) -> dict:
    """
    Generate an inbox warming schedule that ramps up email volume gradually.
    Prevents cold outreach from landing in spam by establishing sender reputation.
    """
    start = datetime.fromisoformat(start_date) if start_date else datetime.now()

    schedule = []
    for day in range(duration_days):
        date = start + timedelta(days=day)
        # Ramp: 5 → target over duration_days using exponential curve
        progress = day / max(duration_days - 1, 1)
        daily_volume = max(5, int(5 + (target_daily_volume - 5) * (progress ** 0.7)))

        schedule.append({
            "day": day + 1,
            "date": date.strftime("%Y-%m-%d"),
            "volume": daily_volume,
            "types": _warming_email_types(day),
            "open_rate_target": f"{min(40 + day * 2, 70)}%",
        })

    return {
        "from_email": from_email,
        "from_name": from_name,
        "duration_days": duration_days,
        "target_daily_volume": target_daily_volume,
        "schedule": schedule,
        "estimated_ready_date": (start + timedelta(days=duration_days)).strftime("%Y-%m-%d"),
        "instructions": [
            "Use a dedicated warming email provider (Mailwarm, Lemwarm, or similar)",
            "Keep SPF, DKIM, DMARC records configured before starting",
            "Monitor spam folder daily — if volume exceeds 5%, pause and investigate",
            "Do NOT send cold outreach during warming period",
            f"Begin outreach after {(start + timedelta(days=duration_days)).strftime('%Y-%m-%d')}",
        ],
    }


def generate_spf_dkim_instructions(domain: str) -> dict:
    """
    Return DNS setup instructions for SPF, DKIM, DMARC — required for deliverability.
    """
    return {
        "domain": domain,
        "spf_record": {
            "type": "TXT",
            "host": "@",
            "value": f"v=spf1 include:sendgrid.net include:mailgun.org ~all",
            "ttl": 3600,
        },
        "dmarc_record": {
            "type": "TXT",
            "host": "_dmarc",
            "value": f"v=DMARC1; p=none; rua=mailto:dmarc@{domain}; ruf=mailto:dmarc@{domain}; fo=1",
            "ttl": 3600,
        },
        "dkim_note": "DKIM keys generated by your email provider (SendGrid/Mailgun). Add the CNAME records they provide.",
        "verification_tools": [
            "https://mxtoolbox.com/spf.aspx",
            "https://www.mail-tester.com",
            "https://dmarcian.com/dmarc-inspector/",
        ],
        "checklist": [
            f"Add SPF TXT record to {domain} DNS",
            "Add DKIM CNAME records from email provider",
            "Add DMARC TXT record",
            "Verify all records at mxtoolbox.com",
            "Send test email to mail-tester.com — target score 9/10+",
            "Start warming schedule only after score 9/10",
        ],
    }


def build_crm_contact(
    name: str,
    email: str,
    company: str,
    title: str,
    source: str = "lead_finder",
    notes: str = "",
    tags: list = None,
) -> dict:
    """
    Structure a lead as a CRM contact record for tracking outreach status.
    """
    return {
        "contact": {
            "name": name,
            "email": email,
            "company": company,
            "title": title,
            "source": source,
            "tags": tags or [],
            "notes": notes,
            "created_at": datetime.now().isoformat(),
        },
        "pipeline": {
            "status": "new",
            "stage": "discovery",
            "next_action": "send_intro_email",
            "next_action_date": (datetime.now() + timedelta(days=1)).strftime("%Y-%m-%d"),
            "touchpoints": [],
        },
    }


def track_outreach(
    contact_email: str,
    action: str,
    outcome: str = "",
    notes: str = "",
) -> dict:
    """
    Log an outreach touchpoint (email sent, reply received, call scheduled).
    action: intro_sent | follow_up_1 | follow_up_2 | break_up | reply_received | meeting_booked | closed_won | closed_lost
    """
    valid_actions = {
        "intro_sent", "follow_up_1", "follow_up_2", "break_up",
        "reply_received", "meeting_booked", "closed_won", "closed_lost",
    }
    if action not in valid_actions:
        return {"error": f"Unknown action '{action}'. Valid: {sorted(valid_actions)}"}

    touchpoint = {
        "email": contact_email,
        "action": action,
        "outcome": outcome,
        "notes": notes,
        "timestamp": datetime.now().isoformat(),
        "next_step": _next_step(action),
    }
    logger.info("Outreach tracked: %s → %s → %s", contact_email, action, outcome)
    return {"tracked": True, "touchpoint": touchpoint}


def _warming_email_types(day: int) -> list:
    types = ["peer_reply"]
    if day >= 3:
        types.append("newsletter_subscribe")
    if day >= 7:
        types.append("content_share")
    if day >= 10:
        types.append("warm_intro")
    return types


def _next_step(action: str) -> str:
    return {
        "intro_sent": "Wait 3 days, then send follow_up_1 if no reply",
        "follow_up_1": "Wait 6 days, then send follow_up_2 or break_up",
        "follow_up_2": "Wait 3 days, then send break_up",
        "break_up": "Mark as closed_lost if no reply within 7 days",
        "reply_received": "Respond within 24 hours, schedule meeting if interested",
        "meeting_booked": "Prepare demo, follow up with notes after meeting",
        "closed_won": "Hand off to onboarding",
        "closed_lost": "Add to nurture list for 6-month follow-up",
    }.get(action, "Review and determine next step")
